# Generated by Django 6.0.6 on 2026-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='price',
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='quotation',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(default='30 Days', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq_title',
            field=models.CharField(default='Office Furniture', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_name',
            field=models.CharField(default='Demo Vendor', max_length=200),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
    ]
